### ISSUE TITLE
easywatch as an extra

### ISSUE THREAD

**Issue by timka** [Ceasar/staticjinja#23]
I‘d like to use only the Jinja templating part since python-livereload and/or webassets already cover FS watching for me. Therefore it would be nice to have easywatch requirement declared as an extra.

However, this may become an issue for projects that depend on staticjinja installed with easywatch by default. Anyway, in timka/staticjinja@1a268eb9274ba871758d4bc3740c43834e2a1a28 I did exactly that, as this is the simplest solution that works for me.

**Comment by Ceasar** [comment]
Just seeing this for the time time now-- almost a year late. My mistake.

I think this is a good idea. The point about the slight backwards incompatibility I think should only be a minor inconvenience for maintainers, since it's not that hard to fix, and most projects I created with this were one-off things. I'll copy your change and credit you for it. Thanks for reporting!

**Comment by NickCrews** [comment]
I believe this is fixed now. Please reopen if not.
