### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by sahuguet** [Ceasar/staticjinja#44]
This article mentions a cool little plugin called livereload.
http://nafiulis.me/making-a-static-blog-with-pelican.html#livereload

That could be a good addition.

**Comment by Ceasar** [comment]
LiveReload is cool, I actually bought a license. However, I wouldn't want to integrate it directly with staticjinja since that would increase the scope of the project more than I would like. However, if someone gets it to work, I'd love to see a section in the documentation describing how to use them together.

**Comment by Ceasar** [comment]
I'm going to close this for now though since it's not actually an issue.
